[package]
name = "sysstat"
version = "0.1.0"
authors = ["shellcodesniper <shellcodesniper@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = '0.9.0'
colour = '0.6.0'
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = '0.4.19'
terminal_size = '0.1.17'